### ISSUE TITLE
A config for 22.05 kHz

### ISSUE THREAD

**Issue by egorsmkv** [vtuber-plan/iSTFTNet#1]
Can you add it to the repo, please?

**Comment by jstzwj** [comment]
OK, I added the 22.05k Hz config.

**Comment by egorsmkv** [comment]
Thanks!

**Comment by egorsmkv** [comment]
@jstzwj Am I right that values in filter_length, hop_length, win_length, and n_mel_channels will remain the same?

**Comment by jstzwj** [comment]
Keeping the same settings as 48k is right. And it is also possible to take half of  filter_length, hop_length, and win_length, which can reduce the model parameters. Meanwhile the upsample rate of transposed convolution should be reduced to half.
I haven't tested whether reducing them to half will harm the quality.

**Comment by egorsmkv** [comment]
I see, thanks @jstzwj !
